all:
	@gcc rnorm.c -o rnorm -lm
	@gcc diagonal.c -o diagonal -lm
	@gcc esquina.c -o esquina -lm
	@echo "Sintaxis: ./diagonal n d c"
	@echo "Sintaxis: ./esquina  n d c"
clean:
	rm rnorm
	rm diagonal
	rm esquina
