all:
	gcc randf.c rnorm.c -o rnorm -lm
	gcc diagonal.c -o diagonal -lm
	gcc randf.c esquina.c -o esquina
	gcc randf.c espirales.c -o espirales
clean:
	rm rnorm; rm diagonal; rm esquina; rm espirales; \
	rm angulos; rm radios; rm espirales.jpg
